import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./context/ModalContext"
import ModalProvider from "./context/ModalContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={" bg-white-100"}
      >
        <ModalProvider>
        {children}
        </ModalProvider>
      </body>
    </html>
  );
}
